import type { SessionType } from './types';

export const sessionTypes: SessionType[] = [
  {
    id: '1',
    value: 'yin1',
    label: 'Yin Yoga Beginner',
    sessionDuration: 60,
    instructorName: 'Sofia Wells',
    yogaTypeId: 'yin',
  },
  {
    id: '2',
    value: 'yin2',
    label: 'Yin Yoga All Levels',
    sessionDuration: 75,
    instructorName: 'Sofia Wells',
    yogaTypeId: 'yin',
  },
  {
    id: '3',
    value: 'yin3',
    label: 'Yin Yoga Pro',
    sessionDuration: 115,
    instructorName: 'Sofia Wells',
    yogaTypeId: 'yin',
  },
  {
    id: '4',
    value: 'kundalini2',
    label: 'Kundalini Yoga All Levels',
    sessionDuration: 90,
    instructorName: 'Ava Hart',
    yogaTypeId: 'kundalini',
  },
  {
    id: '5',
    value: 'kundalini3',
    label: 'Kundalini Yoga Pro',
    sessionDuration: 100,
    instructorName: 'Ava Hart',
    yogaTypeId: 'kundalini',
  },
  {
    id: '6',
    value: 'iyengar1',
    label: 'Iyengar Yoga Beginner',
    sessionDuration: 90,
    instructorName: 'Maya Collins',
    yogaTypeId: 'iyengar',
  },
  {
    id: '7',
    value: 'iyengar3',
    label: 'Iyengar Yoga Pro',
    sessionDuration: 75,
    instructorName: 'Maya Collins',
    yogaTypeId: 'iyengar',
  },
  {
    id: '8',
    value: 'bikram1',
    label: 'Bikram Yoga Beginner',
    sessionDuration: 60,
    instructorName: 'Maya Collins',
    yogaTypeId: 'bikram',
  },
];
